### ISSUE TITLE
Scastie - multiple files support

### ISSUE THREAD

**Issue by rochala** [scalacenter/student-projects#12]
### Description
Scastie is an online Scala playground that allows everyone to write, run, and share Scala programs from their web browser.
Currently, Scastie allows users to edit only single file. This approach has several drawbacks:
- we can’t use macros,
- with increased complexity and size of a snippet, it can be hard to find yourself in the codebase

We would like to adress these issues by allowing users to have multiple files opened with scastie at the same time.
**Corressponding issue:**
https://github.com/scalacenter/scastie/issues/532
### Expected outcome:
Scastie supports editing multiple files allowing us to run macros and separate big snippets into smaller parts.
More specifically:
- There should be proper UI supporting multiple file editing,
- Multiple files should properly be compiled on the server,
- All existing features and snippets should be compatible with new multiple file format,
- There should be IDE support for multiple files.

### Roadmap

- [ ] Add UI for the client to display multiple files
- [ ] Implement logic on the client side to properly store and handle tab switches
- [ ] Handle multiple files on the server side
- [ ] Handle multiple files on the metals side
- [ ] Ensure that old snippets are compatible with the new data schema

### Supervisors
Jędrzej Rochala (jrochala@virtuslab.com): Software engineer at VirtusLab.
